apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: search
    cost-center: e-commerce
    team: shopping-cart-team
    owner: jp@example.com
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          securityContext:
            allowPrivilegeEscalation: false
            privileged: true
            readOnlyRootFilesystem: true
            runAsNonRoot: false
            capabilities:
              add:
                - ALL
          imagePullPolicy: Always